urls.py
from django.conf.urls import url
from renoauth import views


urlpatterns = [
    url(r'test/$', views.test, name='test'),
    url(r'test2/$', views.test2, name='test2'),

    url(r'^$', views.accounts, name='accounts'),

    url(r'^create/$', views.create, name='create'),

    url(r'^email/key/send/$', views.email_key_send, name='email_key_send'),
    url(r'^email/key/confirm/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.email_key_confirm, name='email_key_confirm'),


    url(r'^login/$', views.log_in, name='log_in'),
    url(r'^logout/$', views.log_out, name='log_out'),
    url(r'^logout/done/$', views.log_out_done, name='logout'),

    url(r'^username/change/$', views.username_change, name='username_change'),
    url(r'^username/change/done/$', views.username_change_done, name='username_change_done'),

    url(r'^password/change/$', views.password_change, name='password_change'),
    url(r'^password/change/done/$', views.password_change_done, name='password_change_done'),
    url(r'^password/reset/$', views.password_reset, name='password_reset'),
    url(r'^password/reset/done/$', views.password_reset_done, name='password_reset_done'),
    url(r'^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$', views.password_reset_key,
        name='password_reset_key'),
    url(r'^password/reset/key/done/$', views.password_reset_key_done, name='password_reset_key_done'),

    url(r'^email/add/$', views.email_add, name='email_add'),
    url(r'^email/add/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$', views.email_add_key, name='email_add_key'),
    url(r'^email/add/key/done/$', views.email_add_key_done, name='email_add_key_done'),

    url(r'^email/default/$', views.email_default, name='email_default'),
    url(r'^email/remove/$', views.email_remove, name='email_remove'),
]

forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.conf import settings
from renoauth.models import UserSubUsername, UserSubEmail


class UserCreateForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control ', 'placeholder': 'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                         'placeholder': 'Password_confirm'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Username(ID) or Email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ['username', 'password']


class EmailAddForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control',
                                                            'placeholder': 'enter email to add'}))

    class Meta:
        model = User
        fields = ['email']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'new Password'}))
    new_password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                             'placeholder': 'new Password confirm'}))

    class Meta:
        model = User
        fields = ['password']


class PasswordResetForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Username(ID) or Email'}))

    class Meta:
        model = User
        fields = ['username']


class PasswordResetConfirmForm(forms.ModelForm):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                     'placeholder': 'new Password'}))
    new_password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                             'placeholder': 'new Password confirm'}))

    class Meta:
        model = User
        fields = ['password']


class PasswordCheckBeforeDeactivationForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ['password']


class PasswordCheckBeforeDeleteForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

    class Meta:
        model = User
        fields = ['password']

templates/renoauth/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uid=uid token=token %}
{% endautoescape %}

templates/renoauth/account_activation_invalid.html
{% extends 'base.html' %}



{% block contents %}

The confirmation link was invalid.
{% endblock %}
{% block extra_script %}
<script>

</script>
{% endblock %}

templates/renoauth/account_activation_sent.html
{% extends 'base.html' %}

{% block content %}
  <p>Please confirm your email address to complete the registration. </p>
{% endblock %}

templates/renoauth/accounts.html
{% extends 'base.html' %}



{% block contents %}
    {% if user.is_authenticated %}
    <!--user is authenticated-->

        {% if user.userextension.status == 1010 %}
        <!--USER_EXTENSION_USING_VERIFIED-->
            {% block user_extension_using_verified %}

            {% endblock %}

        {% elif user.userextension.status == 1020 %}
        <!--USER_EXTENSION_USING_NOT_VERIFIED-->
            {% block user_extension_using_not_verified %}

            {% endblock %}

        {% endif %}

    {% else %}
    <!--user is not authenticated-->
    {% endif %}

{% endblock %}
{% block extra_script %}
<script>

</script>
{% endblock %}

templates/renoauth/create.html
{% extends 'base.html' %}
{% block extra_head %}<script src='https://www.google.com/recaptcha/api.js'></script>{% endblock %}

{% block contents %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-offset-2 col-md-8 col-lg-offset-3 col-lg-6">
                <div class="row">

                    <form class="form-horizontal" method="post" action=".">

                        {% csrf_token %}


                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">Username(ID)</label>
                            <div class="col-sm-10">{{ form.username }}</div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_email">Email</label>
                            <div class="col-sm-10">
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-xs-2 col-sm-2" for="id_password">Password</label>
                            <div class="col-sm-10">
                                {{ form.password }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-xs-2 col-sm-2" for="id_password_confirm">Password</label>
                            <div class="col-sm-10">
                                {{ form.password_confirm }}
                            </div>
                        </div>
<!--
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="g-recaptcha" data-sitekey="6Ld4Tz4UAAAAAEnsEF3EcBBdGViccpEQNiA1rBcs"></div>
                            </div>
                        </div>
-->
                        <div class="form-group">
                            <div class="col-xs-offset-5 col-sm-offset-5">
                                <button class="btn btn-default" type="submit">Create</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
                    {% if wrong %}
                        {{ wrong.message }} hello
                    {% endif %}

        </div>
    </div>


{% endblock %}
{% block extra_script %}
<script>
$(document).ready(function () {
    var username_regex = /^[a-zA-Z0-9._]+$/;
    var email_regex = /[^@]+@[^@]+\.[^@]+/;

    $('#id_username').blur(function () {
        var username = $('#id_username').val();
        var username_len_test = !(username.length > 30);
        var username_regex_test = username_regex.test(username);
        var username_result = username_regex_test && username_len_test;
        console.log('username result : '+ username_result);

        var email = $('#id_email').val();
        var email_len_test = !(email.length > 255);
        var email_regex_test = email_regex.test(email);
        var email_result = email_regex_test && email_len_test;
        console.log('email result : '+ email_result);

        var password = $('#id_password').val();
        var password_confirm = $('#id_password_confirm').val();
        console.log('password : ' + password + ' password_confirm : ' + password_confirm);

        /*
        const found = forbidden.find(word => username.includes(word));
        if(found) {
            console.log({'result': found + ' banned username'});
        }
        */

        const forbidden = ['admin', 'master', 'owner'];

        const found = forbidden.find(function (item, index, array) {
            return username.includes(item)
        });

        if(found) {
            console.log({'result': found + ' banned username'})
        }

        /*
        $.ajax({
            url:'/accounts/create/',
            type:'post',
            dataType:'json',
            cache:false,
            data:{
                email_change:'yonginautoland@naver.com'
            },
            success:function (data) {
                console.log('success!')
            }
        });
        */
    });
});
</script>
{% endblock %}

templates/renoauth/create_done.html
{% extends 'base.html' %}
{% block contents %}
    {% if user.userextension.status == 1010 %}
        <!--USER_EXTENSION_USING_VERIFIED-->

    {% elif user.userextension.status == 1020 %}
        <!--USER_EXTENSION_USING_NOT_VERIFIED-->

    {% elif user.userextension.status == 1021 %}
        <!--USER_EXTENSION_USED_UNDER_30DAYS-->

    {% elif user.userextension.status == 1022 %}
        <!--USER_EXTENSION_USED_OVER_30DAYS-->

    {% endif %}
{% endblock %}

templates/renoauth/email_key_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/renoauth/test.html
{% extends 'base.html' %}
{% block extra_head %}<script src='https://www.google.com/recaptcha/api.js'></script>{% endblock %}
{% block contents %}

  <form method="post">
    {% csrf_token %}

    <div class="g-recaptcha" data-sitekey="6Ld4Tz4UAAAAAEnsEF3EcBBdGViccpEQNiA1rBcs"></div>

    <button type="submit" class="btn btn-primary">Post</button>
  </form>

    <button id="btn_test">Test</button>
    <br>
    <input type="text" id="input_test"/>
{% endblock %}
{% block extra_script %}
<script>
$(document).ready(function () {
    $("form").submit(function(event) {
        var recaptcha = $("#g-recaptcha-response").val();
        if (recaptcha === "") {
            event.preventDefault();
            alert("Please check the recaptcha");
        }
    });

    $('#btn_test').click(function () {
        var array_list = ['list_1', {'1dic_key': '1dic_value', '2dic_key': '2dic_value'}, 'list_2', 'list_3'];
        var text_test = $('#input_test').val();
        var regex_test = /^([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?)$/;
        var match_result = regex_test.test(text_test);
        var regex_numeric_test = /^\d+$/;
        var match_result_numeric = regex_numeric_test.test(text_test);

        console.log(match_result);
        console.log('-----------');
        console.log(match_result_numeric);

        //console.log($.type(array_list[0]));
        //console.log($(array_list).size());
        //$.each(data, function (index, item) {
        //    console.log('index : ' + index + ', item : ' + item )
        //    $.each(item, function (index, item) {
        //    })
        //});
    });
});
</script>
{% endblock %}

templates/renoauth/test2.html
{% extends 'base.html' %}
{% block extra_head %}
    <!--<script src='https://www.google.com/recaptcha/api.js'></script>-->
    <style>
    .pace {
  -webkit-pointer-events: none;
  pointer-events: none;
  -webkit-user-select: none;
  -moz-user-select: none;
  user-select: none;
}

.pace-inactive {
  display: none;
}

.pace .pace-progress {
  background: #29d;
  position: fixed;
  z-index: 2000;
  top: 0;
  left: 0;
  height: 2px;

  -webkit-transition: width 1s;
  -moz-transition: width 1s;
  -o-transition: width 1s;
  transition: width 1s;
}

.pace .pace-progress-inner {
  display: block;
  position: absolute;
  right: 0px;
  width: 100px;
  height: 100%;
  box-shadow: 0 0 10px #29d, 0 0 5px #29d;
  opacity: 1.0;
  -webkit-transform: rotate(3deg) translate(0px, -4px);
  -moz-transform: rotate(3deg) translate(0px, -4px);
  -ms-transform: rotate(3deg) translate(0px, -4px);
  -o-transform: rotate(3deg) translate(0px, -4px);
  transform: rotate(3deg) translate(0px, -4px);
}

.pace .pace-activity {
  display: block;
  position: fixed;
  z-index: 2000;
  top: 15px;
  right: 15px;
  width: 14px;
  height: 14px;
  border: solid 2px transparent;
  border-top-color: #29d;
  border-left-color: #29d;
  border-radius: 10px;
  -webkit-animation: pace-spinner 400ms linear infinite;
  -moz-animation: pace-spinner 400ms linear infinite;
  -ms-animation: pace-spinner 400ms linear infinite;
  -o-animation: pace-spinner 400ms linear infinite;
  animation: pace-spinner 400ms linear infinite;
}

@-webkit-keyframes pace-spinner {
  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg); }
}
@-moz-keyframes pace-spinner {
  0% { -moz-transform: rotate(0deg); transform: rotate(0deg); }
  100% { -moz-transform: rotate(360deg); transform: rotate(360deg); }
}
@-o-keyframes pace-spinner {
  0% { -o-transform: rotate(0deg); transform: rotate(0deg); }
  100% { -o-transform: rotate(360deg); transform: rotate(360deg); }
}
@-ms-keyframes pace-spinner {
  0% { -ms-transform: rotate(0deg); transform: rotate(0deg); }
  100% { -ms-transform: rotate(360deg); transform: rotate(360deg); }
}
@keyframes pace-spinner {
  0% { transform: rotate(0deg); transform: rotate(0deg); }
  100% { transform: rotate(360deg); transform: rotate(360deg); }
}
    </style>
{% endblock %}
{% block contents %}
<!--
  <form method="post">
    {% csrf_token %}

    <div class="g-recaptcha" data-sitekey="6Ld4Tz4UAAAAAEnsEF3EcBBdGViccpEQNiA1rBcs"></div>

    <button type="submit" class="btn btn-primary">Post</button>
  </form>
-->
    <button id="btn_test">Test</button>
    <br>
    <input type="text" id="input_test"/>
    <br>
    <div id="div_test"></div>

{% endblock %}
{% block extra_script %}
<script>
$(document).ready(function () {

    $('#btn_send').click(function () {
            var text_email = $('#input_send').val();
            console.log(text_email);
            $.ajax({
                url:'/accounts/test2/',
                type:'post',
                dataType:'json',
                cache:false,
                data:{
                    email:text_email
                },
                success:function (data) {
                    console.log(data)
                }
            });
        });

        // csrf set
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');
        function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                 }
            }
        });

    $("form").submit(function(event) {
        var recaptcha = $("#g-recaptcha-response").val();
        if (recaptcha === "") {
            event.preventDefault();
            alert("Please check the recaptcha");
        }
    });

    $('#btn_test').click(function () {
        var array_list = ['list_1', {'1dic_key': '1dic_value', '2dic_key': '2dic_value'}, 'list_2', 'list_3'];
        var text_test = $('#input_test').val();
        var regex_test = /^([A-Za-z0-9_](?:(?:[A-Za-z0-9_]|(?:\.(?!\.))){0,28}(?:[A-Za-z0-9_]))?)$/;
        var match_result = regex_test.test(text_test);
        var regex_numeric_test = /^\d+$/;
        var match_result_numeric = regex_numeric_test.test(text_test);

        console.log(match_result);
        console.log('-----------');
        console.log(match_result_numeric);
        console.log('-----------');

        $.ajax({
            url:'/accounts/test2/',
            type:'post',
            dataType:'html',
            cache:false,
            success:function (data) {
                console.log(data)
                var headline = $(data.responseText).find('a.tsh').text();
                alert(headline);
                $('#div_test').html(headline)
            }
        });
        //console.log($.type(array_list[0]));
        //console.log($(array_list).size());
        //$.each(data, function (index, item) {
        //    console.log('index : ' + index + ', item : ' + item )
        //    $.each(item, function (index, item) {
        //    })
        //});
    });
});
</script>
{% endblock %}

templates/renoauth/test4.html
<!DOCTYPE html>
<html >
<head>
    <meta charset="UTF-8">
    <title>Animated radial / circular menu</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- 부트스트랩 3.3.7로 버전바꾸니 드랍다운에서 인풋클릭시 사라지는거 해결-->
    <script
    src="https://code.jquery.com/ui/1.9.2/jquery-ui.min.js"
    integrity="sha256-eEa1kEtgK9ZL6h60VXwDsJ2rxYCwfxi40VZ9E0XwoEA="
    crossorigin="anonymous"></script>

<!--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">-->

    <style>
        /* Demo by http://creative-punch.net */


body {
  background: #39D;
}

.circular-menu {
  width: 250px;
  height: 250px;
  margin: 0 auto;
  position: relative;
}

.circle {
  width: 250px;
  height: 250px;
  opacity: 0;

  -webkit-transform: scale(0);
  -moz-transform: scale(0);
  transform: scale(0);

  -webkit-transition: all 0.4s ease-out;
  -moz-transition: all 0.4s ease-out;
  transition: all 0.4s ease-out;
}

.open.circle {
  opacity: 1;

  -webkit-transform: scale(1);
  -moz-transform: scale(1);
  transform: scale(1);
}

.circle a {
  text-decoration: none;
  color: white;
  display: block;
  height: 40px;
  width: 40px;
  line-height: 40px;
  margin-left: -20px;
  margin-top: -20px;
  position: absolute;
  text-align: center;

}

.circle a:hover {
  color: #eef;
}
.hey2 :hover {
  color: #eef;
  -webkit-transform: scale(3);
  -moz-transform: scale(3);
  transform: scale(3);
}
    </style>
</head>

<body style="padding: 80px;">

    <!-- 모바일에선 페이스북처럼 마우스다운후 드래그 + 스캐일로 커지는 효과 + 마우스리브, 여기서 디브 위에서라면 마우스리브 효과 발동, 웹에선 호버및 클릭으로 함
    +버튼을 누르게 되면 이모티콘창은 작아지되 옆에서 검색창 뜨게 함 -->

    <!--웹인 경우 mouseleave 쓰면 편할 것으로 사료됨 -->
    <div class="reaction" style="border-radius: 50%; background-color: blue; width: 40px; height:40px; z-index: 0; left:10%">

        <div class="hey" style="position:absolute; border-radius: 50%; background-color: purple; width: 40px; height:40px; z-index: -1;"></div>
        <div style="position:absolute; border-radius: 50%; background-color: skyblue; width: 40px; height:40px; z-index: -2;"></div>
        <div style="position:absolute; border-radius: 50%; background-color: pink; width: 40px; height:40px; z-index: -2"></div>
        <div class="ho" style="position:absolute; border-radius: 50%; background-color: greenyellow; width: 40px; height:40px; z-index: -2"></div>
        <div class="hey2" style="position:absolute; border-radius: 50%; background-color: coral; width: 40px; height:40px; z-index: -2"></div>

    </div>

</body>
<script>
// Demo by http://creative-punch.net
$(document).ready(function () {
    $('.reaction').mousedown(function () {
        var something = $(this).find('div.hey2');
        something.css({'left': '50%', 'z-index':999,   '-webkit-transform': 'scale(1.5)', '-moz-transform': 'scale(1.5)', 'transform': 'scale(1.5)'});

    });

    $(document).mouseup(function () {
        $('.reaction').find('div').css('left', '10%');
        console.log('dddo')
    });
    $('.hey2').hover(function(){
        $(this).css("background-color", "yellow");
        }, function(){
        $(this).css("background-color", "pink");
    });

});

</script>
</html>

templates/renoauth/test5.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <title>Laymei 환영합니다</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script
    src="https://code.jquery.com/ui/1.9.2/jquery-ui.min.js"
    integrity="sha256-eEa1kEtgK9ZL6h60VXwDsJ2rxYCwfxi40VZ9E0XwoEA="
    crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- recaptcha -->
    <script src='https://www.google.com/recaptcha/api.js'></script>

    {% load static from staticfiles %}
    <script src="{% static 'js/jQuery_csrf.js' %}"></script>

{% if user.is_authenticated %}
<!--
<meta http-equiv="refresh" content="5;url=http://www.homejjang.com/">
-->

{% else %}
{% endif %}

    <style>
        @media screen and (max-width: 768px) {
            /* 모바일에 사용될 스트일 시트를 여기에 작성합니다. */
            .mobile_display_none {
                display: none;
            }
            .mobile_display_block {
                display: block;
            }
        }
    </style>
</head>
<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
            <div class="row">
                <div class="mobile_display_block">
                    <p><h1>Laymei</h1></p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-10">
                    <form method="post" action=".">
                        {% csrf_token %}

                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-default pull-right" name="type" value="send">Submit_send</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <p class="h3">Register</p>
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="row">

                        <button type="submit" class="btn btn-default pull-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

</body>
<script>
    $(document).ready(function () {

    });
</script>
</html>